// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjw_W3OLe6DL-HyTONPrfmtKCUquQsAIA',
    appId: '1:608127452127:android:594dea15b67545e6c3ba6a',
    messagingSenderId: '608127452127',
    projectId: 'petattix',
    storageBucket: 'petattix.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwrlKcFZFVJ7YpfWWaLEPYaQIOG2pDaqc',
    appId: '1:608127452127:ios:e763ad6654084aa7c3ba6a',
    messagingSenderId: '608127452127',
    projectId: 'petattix',
    storageBucket: 'petattix.firebasestorage.app',
    iosBundleId: 'com.petattix.petattix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxf9GCSQoMtP_s824E2KbayyrJ4pUaDVc',
    appId: '1:608127452127:web:b64a6f4c783f4090c3ba6a',
    messagingSenderId: '608127452127',
    projectId: 'petattix',
    authDomain: 'petattix.firebaseapp.com',
    storageBucket: 'petattix.firebasestorage.app',
    measurementId: 'G-DX3PHP0K5P',
  );
}
